# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Wed Sep 10 16:34:45 2014
#      by: PyQt5 UI code generator 5.3.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore,QtGui
from PyQt5 import QtWidgets 
from PyQt5.QtWidgets import QWidget


class Ui_MainWindow(QWidget):
    def __init__(self,parent=None):
        super(Ui_MainWindow,self).__init__(parent)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 730)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphLabels = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphLabels.sizePolicy().hasHeightForWidth())
        self.graphLabels.setSizePolicy(sizePolicy)
        self.graphLabels.setMaximumSize(QtCore.QSize(1200, 31))
        self.graphLabels.setObjectName("graphLabels")
        self.verticalLayout_3.addWidget(self.graphLabels)
        self.graphiScores = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphiScores.sizePolicy().hasHeightForWidth())
        self.graphiScores.setSizePolicy(sizePolicy)
        self.graphiScores.setMaximumSize(QtCore.QSize(1200, 31))
        self.graphiScores.setObjectName("graphiScores")
        self.verticalLayout_3.addWidget(self.graphiScores)
        self.graphPerframe = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphPerframe.sizePolicy().hasHeightForWidth())
        self.graphPerframe.setSizePolicy(sizePolicy)
        self.graphPerframe.setMaximumSize(QtCore.QSize(1200, 31))
        self.graphPerframe.setObjectName("graphPerframe")
        self.verticalLayout_3.addWidget(self.graphPerframe)
        self.log = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        self.log.setMaximumSize(QtCore.QSize(1200, 31))
        self.log.setObjectName("log")
        self.verticalLayout_3.addWidget(self.log)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 1, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMaximumSize(QtCore.QSize(1332, 32))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.horizontalSlider = QtWidgets.QSlider(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(1200, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMaximumSize(QtCore.QSize(51, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.buttonPlay = QtWidgets.QPushButton(self.splitter_2)
        self.buttonPlay.setEnabled(False)
        self.buttonPlay.setIcon(self.style().standardIcon(QtWidgets.QStyle.SP_MediaPlay))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlay.sizePolicy().hasHeightForWidth())
        self.buttonPlay.setSizePolicy(sizePolicy)
        self.buttonPlay.setMaximumSize(QtCore.QSize(67, 32))
        self.buttonPlay.setObjectName("buttonPlay")
        self.gridLayout.addWidget(self.splitter_2, 2, 0, 1, 2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(99, 16))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(108, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.buttonBehavior = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBehavior.sizePolicy().hasHeightForWidth())
        self.buttonBehavior.setSizePolicy(sizePolicy)
        self.buttonBehavior.setMaximumSize(QtCore.QSize(96, 32))
        self.buttonBehavior.setAutoExclusive(False)
        self.buttonBehavior.setAutoDefault(False)
        self.buttonBehavior.setDefault(False)
        self.buttonBehavior.setFlat(False)
        self.buttonBehavior.setObjectName("buttonBehavior")
        self.verticalLayout_2.addWidget(self.buttonBehavior)
        self.buttonNone = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNone.sizePolicy().hasHeightForWidth())
        self.buttonNone.setSizePolicy(sizePolicy)
        self.buttonNone.setMaximumSize(QtCore.QSize(75, 32))
        self.buttonNone.setIconSize(QtCore.QSize(16, 16))
        self.buttonNone.setObjectName("buttonNone")
        self.verticalLayout_2.addWidget(self.buttonNone)
        self.flyInfo = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flyInfo.sizePolicy().hasHeightForWidth())
        self.flyInfo.setSizePolicy(sizePolicy)
        self.flyInfo.setMaximumSize(QtCore.QSize(111, 91))
        self.flyInfo.setObjectName("flyInfo")
        self.verticalLayout_2.addWidget(self.flyInfo)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 233, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonTrain = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTrain.sizePolicy().hasHeightForWidth())
        self.buttonTrain.setSizePolicy(sizePolicy)
        self.buttonTrain.setMaximumSize(QtCore.QSize(86, 32))
        self.buttonTrain.setObjectName("buttonTrain")
        self.verticalLayout_4.addWidget(self.buttonTrain)
        self.buttonPredict = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPredict.sizePolicy().hasHeightForWidth())
        self.buttonPredict.setSizePolicy(sizePolicy)
        self.buttonPredict.setMaximumSize(QtCore.QSize(86, 32))
        self.buttonPredict.setObjectName("buttonPredict")
        self.verticalLayout_4.addWidget(self.buttonPredict)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(196, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 2, 4, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(105, 38))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(105, 37))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBoxPerframe = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxPerframe.sizePolicy().hasHeightForWidth())
        self.comboBoxPerframe.setSizePolicy(sizePolicy)
        self.comboBoxPerframe.setMaximumSize(QtCore.QSize(111, 26))
        self.comboBoxPerframe.setObjectName("comboBoxPerframe")
        self.verticalLayout.addWidget(self.comboBoxPerframe)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(105, 38))
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setEnabled(True)
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMaximumSize(QtCore.QSize(1000000, 1000000))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuVideo = QtWidgets.QMenu(self.menubar)
        self.menuVideo.setObjectName("menuVideo")
        self.menuGo = QtWidgets.QMenu(self.menubar)
        self.menuGo.setObjectName("menuGo")
        self.menuClassifier = QtWidgets.QMenu(self.menubar)
        self.menuClassifier.setObjectName("menuClassifier")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate_Project = QtWidgets.QAction(MainWindow)
        self.actionCreate_Project.setObjectName("actionCreate_Project")
        self.actionLoad_Project = QtWidgets.QAction(MainWindow)
        self.actionLoad_Project.setObjectName("actionLoad_Project")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionImport_Labels = QtWidgets.QAction(MainWindow)
        self.actionImport_Labels.setObjectName("actionImport_Labels")
        self.actionPreviow_Options = QtWidgets.QAction(MainWindow)
        self.actionPreviow_Options.setObjectName("actionPreviow_Options")
        self.actionSwitch_Target = QtWidgets.QAction(MainWindow)
        self.actionSwitch_Target.setObjectName("actionSwitch_Target")
        self.actionSelect_Features = QtWidgets.QAction(MainWindow)
        self.actionSelect_Features.setObjectName("actionSelect_Features")
        self.actionTraining_Parameters = QtWidgets.QAction(MainWindow)
        self.actionTraining_Parameters.setObjectName("actionTraining_Parameters")
        self.actionPredict = QtWidgets.QAction(MainWindow)
        self.actionPredict.setObjectName("actionPredict")
        self.actionCross_Validate = QtWidgets.QAction(MainWindow)
        self.actionCross_Validate.setObjectName("actionCross_Validate")
        self.menuFile.addAction(self.actionCreate_Project)
        self.menuFile.addAction(self.actionLoad_Project)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionImport_Labels)
        self.menuVideo.addAction(self.actionPreviow_Options)
        self.menuGo.addAction(self.actionSwitch_Target)
        self.menuClassifier.addAction(self.actionSelect_Features)
        self.menuClassifier.addAction(self.actionTraining_Parameters)
        self.menuClassifier.addAction(self.actionPredict)
        self.menuClassifier.addAction(self.actionCross_Validate)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuVideo.menuAction())
        self.menubar.addAction(self.menuGo.menuAction())
        self.menubar.addAction(self.menuClassifier.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonPlay.setText(_translate("MainWindow", "Play"))
        self.label.setText(_translate("MainWindow", "Behavior Types:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Multi Fly"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Female"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Chase"))
        self.buttonBehavior.setText(_translate("MainWindow", "Behavior"))
        self.buttonNone.setText(_translate("MainWindow", "None"))
        self.buttonTrain.setText(_translate("MainWindow", "Train"))
        self.buttonPredict.setText(_translate("MainWindow", "Predict"))
        self.label_2.setText(_translate("MainWindow", "Labels"))
        self.label_3.setText(_translate("MainWindow", "Scores"))
        self.label_4.setText(_translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuVideo.setTitle(_translate("MainWindow", "Video"))
        self.menuGo.setTitle(_translate("MainWindow", "Go"))
        self.menuClassifier.setTitle(_translate("MainWindow", "Classifier"))
        self.actionCreate_Project.setText(_translate("MainWindow", "Create Project"))
        self.actionLoad_Project.setText(_translate("MainWindow", "Load Project"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionImport_Labels.setText(_translate("MainWindow", "Import Labels"))
        self.actionPreviow_Options.setText(_translate("MainWindow", "Previow Options"))
        self.actionSwitch_Target.setText(_translate("MainWindow", "Switch Target"))
        self.actionSelect_Features.setText(_translate("MainWindow", "Select Features"))
        self.actionTraining_Parameters.setText(_translate("MainWindow", "Training Parameters"))
        self.actionPredict.setText(_translate("MainWindow", "Predict"))
        self.actionCross_Validate.setText(_translate("MainWindow", "Cross Validate"))

